resources:
- name: file-repo
  type: git
  source:
    branch: master
    paths: []
    uri: https://phartz.dedyn.io/gogs/phartz/service-broker-cli
    username: {{git-username}}
    password: {{git-password}}

jobs:

- name: make
  public: true
  plan:
  - get: file-repo
    trigger: true
  - task: make
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phartz/hugo
      inputs:
        - name: file-repo
      run:
        path: make
        args: []
  - task: test-main
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phartz/hugo
      inputs:
        - name: file-repo
      run:
        path: go
        args: 
          - test
  - task: test-sbclient
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phartz/hugo
      inputs:
        - name: file-repo
      run:
        path: sh
        args:
        - -exc
        - |
        - cd tests
        - go test
