resources:
- name: file-repo
  type: git
  source:
    branch: master
    paths: []
    uri: https://phartz.dedyn.io/gogs/phartz/service-broker-cli.git
    username: {{git-username}}
    password: {{git-password}}

jobs:

- name: test
  public: true
  plan:
  - get: file-repo
    trigger: true
  - task: make
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phartz/hugo
      inputs:
        - name: file-repo
      run:
        path: sh
        args: 
          - -exc
          - |
            mkdir -p /go/src/phartz.dedyn.io/gogs/phartz
            cp -R file-repo/ /go/src/phartz.dedyn.io/gogs/phartz/service-broker-cli
            cd /go/src/phartz.dedyn.io/gogs/phartz/service-broker-cli
            go get golang.org/x/crypto/ssh/terminal
            go test
            cd tests
            go test

- name: build
  public: true
  plan:
  - get: file-repo
    trigger: true
    passed: [test]
  - task: make
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phartz/hugo
      inputs:
        - name: file-repo
      run:
        path: sh
        args: 
          - -exc
          - |
            mkdir -p /go/src/phartz.dedyn.io/gogs/phartz
            cp -R file-repo/ /go/src/phartz.dedyn.io/gogs/phartz/service-broker-cli
            cd /go/src/phartz.dedyn.io/gogs/phartz/service-broker-cli
            go get golang.org/x/crypto/ssh/terminal
            make pipeline_build
